steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Retrieve the secret from Secret Manager and write it to credentials.json
        gcloud secrets versions access latest --secret=minatku_cloud_storage --project=minatku --format='json' | jq -r '.payload.data' | base64 --decode > /workspace/credentials.json
        gcloud secrets versions access latest --secret=db-credentials --project=minatku --format='json' | jq -r '.payload.data' | base64 --decode > /workspace/credentials.json
        gcloud secrets versions access latest --secret=jwt-secret-key --project=minatku --format='json' | jq -r '.payload.data' | base64 --decode > /workspace/jwt-secret-key.json


  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/minatku-cc', '-f', 'Dockerfile', '.' ]
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/minatku-cc']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy minatku-cc \
          --image gcr.io/$PROJECT_ID/minatku-cc \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated

# Store images
#images:
 # - 'gcr.io/$PROJECT_ID/minatku-cc'
options:
  logging: CLOUD_LOGGING_ONLY
